env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
release:
  draft: true
  discussion_category_name: General
builds:
  - id: win-x86/64
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - windows
    goarch:
      - 386
      - amd64
    goarm:
      - 7
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/Mrs4s/go-cqhttp/coolq.Version=v{{.Version}}
    hooks:
      pre:
        - go install github.com/josephspurrier/goversioninfo/cmd/goversioninfo@latest
        - go generate .
  - id: win-arm
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - windows
    goarch:
      - arm
      - arm64
    goarm:
      - 7
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/Mrs4s/go-cqhttp/internal/base.Version=v{{.Version}}
    hooks:
      pre: rm -f resource.syso
  - id: nowin
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 7
    ignore:
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: 386
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/Mrs4s/go-cqhttp/coolq.Version=v{{.Version}}
    hooks:
      pre: rm -f resource.syso

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - fix typo
      - Merge pull request
      - Merge branch
      - Merge remote-tracking
      - go mod tidy

archives:
  - id: binary
    builds:
      - win-x86/64
      - win-arm
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        format: binary
  - id: nowin
    builds:
      - nowin
      - win-x86/64
      - win-arm
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - src: modules/config/default_config.yml
        dst: .
        strip_parent: true
      - src: qqrobot/config.toml
        dst: .
        strip_parent: true

nfpms:
  - license: AGPL 3.0
    homepage: https://go-cqhttp.org
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - deb
      - rpm
    maintainer: Mrs4s
